// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiapQyv97CPMj_iQ7KJGG39LkhhraXWmM',
    appId: '1:814242481977:web:d2af1bd3e7ffef31330ae8',
    messagingSenderId: '814242481977',
    projectId: 'realtime-34e55',
    authDomain: 'realtime-34e55.firebaseapp.com',
    databaseURL: 'https://realtime-34e55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-34e55.firebasestorage.app',
    measurementId: 'G-SXS30V3MNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYzLGitsMgYdJ3dJhAdQyzj59UAFsWzM0',
    appId: '1:814242481977:android:d0df5219b8e83b02330ae8',
    messagingSenderId: '814242481977',
    projectId: 'realtime-34e55',
    databaseURL: 'https://realtime-34e55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-34e55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBJV0iOau7EK5lRZRjiZcSv1-S8ydTtTo',
    appId: '1:814242481977:ios:9cf8965eec05b0b4330ae8',
    messagingSenderId: '814242481977',
    projectId: 'realtime-34e55',
    databaseURL: 'https://realtime-34e55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-34e55.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBJV0iOau7EK5lRZRjiZcSv1-S8ydTtTo',
    appId: '1:814242481977:ios:9cf8965eec05b0b4330ae8',
    messagingSenderId: '814242481977',
    projectId: 'realtime-34e55',
    databaseURL: 'https://realtime-34e55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-34e55.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiapQyv97CPMj_iQ7KJGG39LkhhraXWmM',
    appId: '1:814242481977:web:e71eb9ae43ead8c5330ae8',
    messagingSenderId: '814242481977',
    projectId: 'realtime-34e55',
    authDomain: 'realtime-34e55.firebaseapp.com',
    databaseURL: 'https://realtime-34e55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-34e55.firebasestorage.app',
    measurementId: 'G-0J301CVTY6',
  );
}
