// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdb49LZYoZpzHpW6X_pKO3VFhm7bLWRz4',
    appId: '1:164097534241:web:9de7248bd32b37c1a8b660',
    messagingSenderId: '164097534241',
    projectId: 'smart-health-scale',
    authDomain: 'smart-health-scale.firebaseapp.com',
    storageBucket: 'smart-health-scale.firebasestorage.app',
    measurementId: 'G-MNXSL57P4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzDbyMiz_ty5U6HG8NcrboslLkmXiy6bM',
    appId: '1:164097534241:android:64f639cbf5b7d067a8b660',
    messagingSenderId: '164097534241',
    projectId: 'smart-health-scale',
    storageBucket: 'smart-health-scale.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy0psd64RuzsYGeTf7xe2BniTE4V2T1yg',
    appId: '1:164097534241:ios:476419ddd3660048a8b660',
    messagingSenderId: '164097534241',
    projectId: 'smart-health-scale',
    storageBucket: 'smart-health-scale.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdb49LZYoZpzHpW6X_pKO3VFhm7bLWRz4',
    appId: '1:164097534241:web:c260d23deb650f17a8b660',
    messagingSenderId: '164097534241',
    projectId: 'smart-health-scale',
    authDomain: 'smart-health-scale.firebaseapp.com',
    storageBucket: 'smart-health-scale.firebasestorage.app',
    measurementId: 'G-T4X1053DZ8',
  );
}
